// Auto-generated by AFM VFCC CMS — do not edit manually
window.churchData = {
  "events": [],
  "blogs": [
    {
      "title": "Testing",
      "author": "Ramudzuli Ralidzhivha",
      "date": "18 Apr 2026",
      "content": "Christ is Lord"
    }
  ]
};
