// Auto-generated by AFM VFCC CMS — do not edit manually
window.churchData = {
  "events": [],
  "blogs": [
    {
      "title": "New Blog Post",
      "author": "RR Ralidzhivha",
      "date": "16 May 2026",
      "content": "Content"
    }
  ]
};
