// Auto-generated by AFM VFCC CMS - do not edit manually
window.churchData = {
  events: [
    {title:'Youth Human Rights Day Car Wash',desc:'The youth ministry will be hosting a car wash this coming Saturday to celebrate Human Rights Day.',date:'19 Mar 2026',image:'posters/1773884200566_White And Blue Illustrative Car Wash Flyers.png'},
  ],
  blogs: [
    {title:'Always be prayerful',author:'Ralidzhivha RR',date:'19 Mar 2026',content:'It is important that we always equip ourselves with prayer.'},
  ]
};
